### ISSUE TITLE
Should document the error - Please, set "CHROME_BIN"?

### ISSUE THREAD

**Issue by felquis** [ReactTraining/react-point#14]
```
No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
```

I'm on Linux Mint, with only Firefox installed.

**Comment by felquis** [comment]
Just installed Chrome and it worked well.

**Comment by mjackson** [comment]
I assume you're trying to run the tests? If so, glad you figured it out. But it's not something that we need to document for users of the library.
