### ISSUE TITLE
The Point?

### ISSUE THREAD

**Issue by kennetpostigo** [ReactTraining/react-point#2]
I'm not quite sure what the point of the component is, I read the README and I didn't quite get it. Initially I thought the component was to tell you when your hovering/pointing over an element. I think I'm wrong about that. Could it be to normalize touch and click events on elements? Sorry if its a bad question lol 😄

**Comment by mjackson** [comment]
> Could it be to normalize touch and click events on elements?

Yep, nailed it. I needed a word for click/tap and chose "point". Some people use "select", but I wanted to avoid confusion with `<select>`.
